repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.6
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: pylint-src
        name: pylint-src
        entry: tools/lint/pylint_src.sh
        language: system
        pass_filenames: false
